---
title: "Categorical Sequence Analysis with Optimal Matching: An Application with Data from the 'Women 40+ Healthy Aging Study'"
author: 'Adriana Clavijo Daza'
date: 'June 2023'
institution: 'University of Bern'
# division: ''
# advisor: ''
altadvisor: 'Serena'
department: 'Statistics'
degree: 'Master in Statistics and Data Science'
knit: bookdown::render_book
# site: bookdown::bookdown_site

# The next two lines allow you to change the spacing in your thesis. You can 
# switch out \onehalfspacing with \singlespacing or \doublespacing, if desired.
header-includes:
    - \usepackage{setspace}\onehalfspacing
    - \usepackage{algpseudocode}

# Remove the hashtag to specify which version of output you would like.
# Can only choose one at a time.
output:
  thesisdown::thesis_pdf: default 
#  thesisdown::thesis_gitbook: default         
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default

# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 25-39 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("prelims/00-abstract.Rmd"), collapse = "\n  ")`

# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab 
# is needed on the line after the `|`.
acknowledgements: |
  I want to thank a few people.
dedication: |
  You can have a dedication here if you wish. 
preface: |
  This is an example of a thesis setup to use the reed thesis document class 
  (for LaTeX) and the R bookdown package, in general.

# Note that abbreviations in lowercase letters will NOT be automatically
# capitalized.
# abbreviations:
#   ABC: American Broadcasting Company
#   CBS: Colombia Broadcasting System
#   CUS: Computer User Services
#   PBS: Public Broadcasting System
#   NBC: National Broadcasting Company

# Specify the location of the bibliography below
bibliography: bib/thesis.bib

# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
lot: true
lof: true
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete the 
section entirely, or silence them (add # before each line). 

If you have other LaTeX packages you would like to include, delete the # before
header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file
enclose it in a block like this.

If you receive a duplicate label error after knitting, make sure to delete the
index.Rmd file and then knit again.
-->

```{r packages, include = FALSE}
library(readxl)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(TraMineR)
library(TraMineRextras)
library(cluster)
```

```{r helpers, include = FALSE}
## Note: this is order dependent.
source("helpers/distance_matrix.R", local = knitr::knit_global())
source("helpers/predict_scores.R", local = knitr::knit_global())
source("helpers/get_MSE.R", local = knitr::knit_global())
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 7.5,
  fig.height = 5.25
)

options(width = 80)
```

<!--
The acknowledgments, preface, dedication, and abstract are added into the PDF
version automatically by inputting them in the YAML at the top of this file.
Alternatively, you can put that content in files like 00--prelim.Rmd and
00-abstract.Rmd like done below.
-->

```{r eval = !knitr::is_latex_output(), child = here::here("prelims", "00--prelim.Rmd")}
```

```{r eval = !knitr::is_latex_output(), child = here::here("prelims", "00-abstract.Rmd")}
```

```{r, child = "data_prep.Rmd"}
```

```{r, child = "main_analysis.Rmd"}
```

<!-- The {.unnumbered} option here means that the introduction will be 
"Chapter 0." You can also use {-} for no numbers on chapters.
-->

# Introduction {.unnumbered}
