---
title: "Untitled"
author: "Adriana Clavijo Daza"
date: "2023-05-30"
output: html_document
---

```{r base_results, cache = TRUE}
results <- distance_matrix(
  data = rh_data,
  cm_method = "TRATE",
  dm_norm = "maxlength",
  extras_out = TRUE
)

cm_names <- c(1:10, "NA")

cost_matrix_base <- cbind(cm_names, data.frame(results$cm))

colnames(cost_matrix_base) <- c("State", cm_names)
```

```{r clustering, cache = TRUE}
cluster_ward <- hclust(d = as.dist(results$dm), method = "ward.D2")

clusters4 <- cutree(cluster_ward, k = 4)

clusters4_labels <- factor(clusters4, labels = paste("Cluster", 1:4))

clusters4_counts <- tibble(clusters4) %>%
  group_by(clusters4) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  rename(Cluster = clusters4)

clusters2 <- cutree(cluster_ward, k = 2)

clusters2_labels <- factor(clusters2, labels = paste("Cluster", 1:2))
```

```{r BFI_data_prep, cache = TRUE}
BFI_data <- read_excel("../Data_original/Adriana_BFI.xlsx")

BFI_data <- BFI_data %>%
  select(
    PersCode,
    starts_with("BFI")
  )

pers_descrip <- BFI_data %>%
  select(
    PersCode,
    ends_with("mean")
  ) %>%
  pivot_longer(
    cols = ends_with("mean"),
    names_to = "Personality trait",
    values_to = "Value"
  ) %>%
  group_by(`Personality trait`) %>%
  summarise(
    Min = min(Value, na.rm = TRUE),
    Max = max(Value, na.rm = TRUE),
    Average = mean(Value, na.rm = TRUE),
    `Std. deviation` = sd(Value, na.rm = TRUE)
  ) %>%
  ungroup()

pers_descrip[, 1] <- c(
  "Agreeableness", "Conscientiousness",
  "Extraversion", "Neuroticism", "Openness"
)

# knitr::kable(pers_descrip, digits = 2) %>%
#   kableExtra::kable_styling(font_size = 8)
```

```{r, cache = TRUE}
data_all <- tibble(
  Id = colnames(results$dm), Cluster_4 = clusters4_labels,
  Cluster_2 = clusters2_labels
) %>%
  left_join(BFI_data, by = c("Id" = "PersCode")) %>%
  select(Id, Cluster_4, Cluster_2, ends_with("mean")) %>%
  filter(!is.na(BFI_extraversion_mean))

data_all_long <- data_all %>%
  pivot_longer(
    cols = starts_with("BFI"), names_to = "Trait",
    names_prefix = "BFI_", values_to = "Trait_value"
  ) %>%
  mutate(
    Trait = case_when(
      Trait == "extraversion_mean" ~ "Extraversion",
      Trait == "agreeableness_mean" ~ "Agreeableness",
      Trait == "conscientiousness_mean" ~ "Conscientiousness",
      Trait == "neuroticism_mean" ~ "Neuroticism",
      Trait == "openness_mean" ~ "Openness",
      TRUE ~ "other"
    ),
    Cluster_4 = sub("Cluster ", "", Cluster_4),
    Cluster_2 = sub("Cluster ", "", Cluster_2)
  )
```

```{r data_split, cache = TRUE}
set.seed(123)
n <- dim(data_all)[1]
size <- round(n * 0.3)
max_neighbors <- 80

test_set <- sample.int(n, size)
train_set <- (1:n)[-test_set]

test_names <- colnames(results$dm)[test_set]
train_names <- colnames(results$dm)[train_set]
```

```{r base_prediction, cache = TRUE}
base_MSE <- get_MSE(
  data = rh_data,
  prediction_data = data_all,
  train_names = train_names,
  test_names = test_names,
  max_neighbors = 80,
  cm_method = "TRATE",
  dm_norm = "maxlength"
)
```

```{r trivial_MSE, cache = TRUE}
train_means <- data_all_long %>%
  filter(Id %in% train_names) %>%
  rename(Score = Trait) %>%
  group_by(Score) %>%
  summarise(Average = mean(Trait_value)) %>%
  ungroup()

trivial_MSE <- data_all_long %>%
  rename(Score = Trait) %>%
  filter(Id %in% test_names) %>%
  left_join(train_means, by = "Score") %>%
  mutate(sq_difference = (Trait_value - Average)^2) %>%
  group_by(Score) %>%
  summarise(MSE = mean(sq_difference)) %>%
  ungroup()
```

```{r additional_experiments, cache = TRUE}
c_mod <- max(results$cm[results$cm < 2])

experiments <- tibble::tribble(
  ~cm_method, ~dm_norm, ~constant, ~missing_cost, ~min_age, ~max_age,
  "TRATE", "maxlength", NULL, NULL, NULL, NULL,
  "TRATE", "maxlength", c_mod, NULL, NULL, NULL,
  "TRATE", "gmean", NULL, NULL, NULL, NULL,
  "FUTURE", "maxlength", NULL, NULL, NULL, NULL,
  "INDELS", "maxlength", NULL, NULL, NULL, NULL,
  "INDELSLOG", "maxlength", NULL, NULL, NULL, NULL,
  "FUTURE", "gmean", NULL, NULL, NULL, NULL,
  "FUTURE", "gmean", NULL, 1, NULL, NULL,
  "FUTURE", "gmean", NULL, NULL, 20, 55,
  "FUTURE", "gmean", NULL, NULL, 20, 40,
  "FUTURE", "gmean", NULL, 1, 20, 55,
  "FUTURE", "gmean", NULL, 0.5, 20, 55,
)
```

```{r experiments_evaluation, cache = TRUE}
eval_experiments <- experiments %>%
  dplyr::rowwise() %>%
  mutate(result = list(get_MSE(
    data = rh_data,
    prediction_data = data_all,
    train_names = train_names,
    test_names = test_names,
    max_neighbors = 100,
    cm_method = cm_method,
    dm_norm = dm_norm,
    constant = constant,
    missing_cost = missing_cost,
    min_age = min_age,
    max_age = max_age
  )))
```

```{r experiments_results, cache = TRUE}
my_exp <- eval_experiments %>%
  tibble::add_column(Scenario = 1:12) %>%
  select(Scenario, result) %>%
  tidyr::unnest(result) %>%
  group_by(Scenario, Score) %>%
  slice_min(order_by = MSE, n = 1) %>%
  ungroup() %>%
  mutate(Improvement = (1 - (MSE / Trivial)) * 100)
```
