# Distance-based Methods for Categorical Sequences {#background}

Distance-based methods are a class of statistical techniques that use a distance matrix between observed data points as input to perform a specific task. The main idea behind these methods is to capture the structure of the data through a distance measure. Distance-based methods are used in both unsupervised and supervised learning. For example, different variations of clustering, dimensionality reduction and multidimensional scaling can be employed to describe the data, or we can apply $k$-nearest neighbors ($k$-NN) when we are interested in using the data to predict other variable for which we have observed values.

Moreover, in case the obtained distance matrix of (squared) pair-wise distances is Euclidean, we can obtain centered inner products and this allows us to have several other techniques at our disposal, such as $k$-means clustering, principal component anlaysis (PCA), linear discriminant analysis and support vector machines (SVM), see @ESLII.

Distance-based methods have the advantage of allowing applications with a variety of data types, in particular, categorical sequences, i.e. sequences that take values in a finite set of categories or states and are indexed by time.


## Distance Measures for Categorical Sequences

Several ways to compute distances between categorical sequences have been proposed in the context of natural language processing and bioinformatics. Particularly, a class of measures, known as _edit distances_, provide a quantification of the dissimilarity of a pair of sequences by counting the minimum number of operations required to obtain a sequence from the other. For instance, @Hamming-1950 proposed a distance for sequences of the same length that counts the number of positions with different states. @Levenshtein-1966 generalized the Hamming distance to sequences of different lengths by considering the minimum number of single character edits required, namely insertion, deletion and substitution. The Damerau-Levenshtein distance allows for an additional operation known as transposition or swaping of characters (@Damerau-1964). The Jaro-Winkler similarity measure counts the number of matches and transpositions but does not fulfill the triangle inequality (@Winkler-1990). Additionally, there are several algorithms to find the longest common subsequence of a pair of subsequences (see @Bergroth-2000), this could be seen as a measure that allows for insertion and deletion but not substitution nor transposition.

Also, note that from fundamental statistical methods for categorical data, considering the distribution of the states in a sequence, for a pair of sequences, the euclidean or $\chi^2$ distance can be obtained from a pair of frequency vectors which allows us to use them in this context.


## Optimal Matching and Applications

One generalization of the Levenshtein distance that allows for different substitution penalties for every pair of states is the Needleman-Wunsh algorithm, developed by @Needleman-Wunsch-1970 with the aim of comparing and finding similarities between biological sequences (for example, DNA or protein sequences). This algorithm is an application of dynamic programming, an iterative method that simplifies an optimization problem by breaking it into a recursion of smaller problems that are simpler to solve. By choosing the optimal operation at each step, it is guaranteed that the overall solution is optimal as well. An adaptation of this algorithm that works with dissimilarities instead of similarities is known as _optimal matching_ (OM), introduced in social sciences by @Abbott-1986 and widely applied in sociology. OM has been employed in several studies tracking the professional development of specific groups of people, see @Chan-1995, @Torsten-2014 or @Gubler-2015, and to analyze life course data, for example, @Widmer-2009 or @Bastin-2015.

Limitations of OM have been pointed out by some critics. A notable flaw raised by @Wu-2000 lies in the definition of the cost matrix — a core hyperparameter of the method — and the strong assumption about its symmetry. Initially, the method considered substitution costs that were provided by an expert in the context. However, data-based aproaches for the calculation of the cost matrix have been proposed since then, see @Studer-2016.

Once a distance matrix has been obtained via OM or any other technique that is applicable to categorical sequences, a distance-based method can be used depending on the specific interest of the research. Usually, clusters are obtained in order to identify common trajectories through visual inspection, @Abbott-1983 highlighted the possibility to use the distance matrix for multidimensional scaling, @Gabadinho-2013 proposed a way to identify typical patterns based on the coverage neighborhood of the sequences applied to childbirth histories, @Massoni-2009 combined OM and self-organizing maps in the study of career path and employability. In addition, @Studer-2011 proposed a methodology to analyze how covariates can explain the discrepancy between sequences based on their dissimilarities and @Han-1999 used the groups obtained via clustering analysis of career trajactories to predict the age of retirement.  

In this work, we are interested in studying the effect of different hyperparameters when using OM to obtain pairwise distances of a group of sequences and subsequently employ them in distance-based methods. Particularly, we consider the effects on both clustering (unsupervised learning) and variable prediction with $k$-NN (supervised learning). For this purpose we analyze a new real-world dataset that includes categorical sequences, auxiliary information and other variables of interest: data from the "Women 40+ Healthy Aging Study".


## Women 40+ Healthy Aging Study

As part of the Women 40+ Healthy Aging Study (see @Fiacco-2020), a large study that was conducted by the Department of Clinical Psychology and Psychotherapy of the University of Zurich, a psychometric instrument was developed in order to obtain information about the history of romantic relationships of women: the categorical sequence of interest.

The study was conducted between June 2017 and February 2018 with women between 40 and 75 years who (self-)reported good, very good or excellent health condition and the absence of acute or chronic somatic disease or mental disorder. The participants who reported psychotherapy or psychopharmacological treatment in the previous 6 months, as well as habitual drinkers, were excluded. Other exclusion criteria were pregnancy in the last 6 months, premature menopause, surgical menopause, intake of hormonal treatment (including contraceptives), shift-work and recent long-distance flight. The participants were recruited from the general population using online advertisement and flyers.

The questionnaire asked the participants to provide information about relationship phases starting from the age of 15 years until the current age at the time of the data collection. The phases were defined by the start and end age and for each phase and information about civil status, relationship status, living situation, children and quality of the relationship was collected. Before including the data corresponding to their own history, the participants were prompted to answer some of the questions based on an example. Some of the participants were excluded when the example entries were not correctly filled. After data cleaning and revisions for consistency the total number of individuals considered in this work is 239.

Additionally, personality scores for the women included in the study are available. Personality refers to the enduring characteristics and behavior that comprise the unique adjustment to life of a person, including major traits, interests, drives, values, self-concept, abilities, and emotional patterns (see @Annett-2008). These scores are obtained via psychometric instruments and evaluate the main personality traits:

- Agreeableness
- Conscientiousness 
- Extraversion
- Neuroticism
- Openness

\par
One of our goals is to obtain groups of similar sequences that allow us to recognize typical relationship trajectories or behaviours of women over 40 years old. For this purpose, we apply a hierarchical agglomerative clustering analysis using Ward's method to minimize the dispersion within the clusters (@Murtagh-2014), using the method `"ward.D2"` of the `hclust` function in `R`. 

On the other hand, we want to explore potential associations between relationship history of women and their personality scores which is of special interest for experts in psychology. The distance-based method chosen for prediction is $k$-NN, as for implementation we use the function `k.nearest.neighbors` from the `R` package `FastKNN`. 


## k-Nearest Neighbors 

$k$-nearest neighbors is a non-parametric prediction method that is based on the assumption that close points behave similarly. Its origin can be traced to 1951 with an unpublished work about non-parametric pattern classification (see @Fix-1989) and was later expanded by @Cover-1967, who provided an upper bound to the probability of classification error. $k$-NN has been recently used in psychology for classification of human emotions, see for instance @Xie-2021 and @Satyanarayana-2022 but also in biology for detection of genomic mutations, see @Xie-2021.

Given a training set $\mathcal{D} = {(x_1, y_1), (x_2, y_2), \dots, (x_n, y_n)}$ of $n$ labeled data points, where $x_i \in \mathcal{X}$ and $y_i \in \mathcal{Y}$, a finite set of class labels for classification or a continuous range of values for regression. $k$-NN provides a way to predict the label or value for a new, data point $x_{n+1}$ (for which $y_{n+1}$ is unknown) by finding the $k$ training data points closest to $x_{n+1}$ and taking a majority vote of their labels (for classification) or averaging the values of $Y$ (for regression). That is, for a given distance function $d(\cdot, \cdot)$ we predict $y_{n+1}$ as:

\begin{equation}
  \hat{y}_{n+1} = \frac{1}{k} \sum_{j=1}^k y_{(j)}
\end{equation}

where $j = {(1), \dots, (k)}$ index the nearest $k$ neighbors of $x_{n+1}$:

\begin{equation}
  d(x_{(1)} , x_{n+1}) < \dots < d(x_{(k)} , x_{n+1}) <         
  d(x_{(k+1)} , x_{n+1}) < \dots < d(x_{(n)} , x_{n+1})
\end{equation}

There are different choices for the distance function $d(\cdot, \cdot)$. For instance, the Euclidean or Mahalanobis distances are common choices. In the case, of categorical sequences, we apply the more general OM algorithm to obtain a dissimiliraty matrix.

In what follows we describe the OM algorithm in detail, including hyperparameters: the cost matrix and normalization functions.


## Distance and Dissimilarity

Given a function $d: \mathcal{X} \times \mathcal{X} \rightarrow [0, \infty)$ and $x, y, z \in \mathcal{X}$, the following properties are defined.

- $d(x, y) \geq 0$ and $d(x, y) = 0 \iff x = y$
- $d(x, y) = d(y, x)$
- $d(x, y) \leq d(x, z) + d(z, y)$

The last property is known as the triangle inequality. If a function $d$ fulfills all the properties above, we say it is a distance measure. However, if the triangle inequality is not fulfilled, then we say $d$ is a dissimilarity measure.